### ISSUE TITLE
Improve project health [meta bug]

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/sw-helpers#48]
There are a number of project health improvements we could make to the current setup:
- [x] **[Make the failing tests pass](https://github.com/GoogleChrome/sw-helpers/issues/50)** - it's harder to understand the impact of new changes (and existing issues) with sub-projects when the tests have been failing for a while. Let's see if we can get them passing again before adding in new work. Right now it's hard to understand when the tests last actually went green (maybe [3 months ago](https://travis-ci.org/GoogleChrome/sw-helpers/builds/147627696)? :))
- [x] **[Consider scoping tests to supported browsers](https://github.com/GoogleChrome/sw-helpers/issues/51)** - when running `--project=sw-offline-google-analytics` I see a lot of tests failing in Safari (which doesn't support Service Worker). Selenium assistant can find any and all browsers available, we just need to check them against a browserId.
- [x] **Provide more insight into build health per project** - I believe we currently only display a single build status for our CI for the overall repo. I'd like to suggest we also include badges for individual projects in the README so folks can instantly tell what is green and what is not.
- [x] **[Decide on build artifacts](https://github.com/GoogleChrome/sw-helpers/issues/52)** - users have asked for us to consider including minified builds in our npm packages (#31). It would be good to decide on this so we can consistently apply it across the subprojects.
- [x] **Get linting to pass** - This has [just](https://github.com/GoogleChrome/sw-helpers/pull/46) been done as part of the work on docs.

**Comment by gauntface** [comment]
@addyosmani I'm going to close this now that we have shields on the homepage for each project.
